### ISSUE TITLE
教程资源

### ISSUE THREAD

**Issue by ZinuoCai** [RenDong3/OpenCV_Notes#1]
你好：请问有好的教程推荐吗

**Comment by rendong3** [comment]
我的笔记参考的书籍名称为《OpenCV3 计算机视觉》、《OpenCV-Python中文教程》，不过都是针对opencv3版本，比较推荐学习opencv4版本，对于一些电子教程，我看的比较少，也不做过多推荐了，不过建议以一些感兴趣的项目为导向进行学习！

**Comment by ZinuoCai** [comment]
谢谢
